# SPDX-FileCopyrightText: 2024 Dom Rodriguez <shymega@shymega.org.uk>
#
# SPDX-License-Identifier: GPL-3.0-only

name: "Update flakes"
on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "0 7 1,15 * *"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  update-nix-flake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: sudo apt-get install -y qemu-user-static
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            extra-platforms = aarch64-linux armv6l-linux armv7l-linux i686-linux riscv64-linux
      - name: Update Flake inputs
        run: nix flake update
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v8
        with:
          commit-message: "chore(deps): Update Flake inputs"
          committer: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          signoff: true
          branch: chore/flake-updates
          delete-branch: true
          title: "chore(nix): Update Flake inputs"
          branch-suffix: "short-commit-hash"
          reviewers: "shymega"
          assignees: "shymega"
          body: |
            Update Flake inputs (Nix)
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
